version: 2

conda:
    environment: doc/environment.yml

build:
   image: latest
   apt_packages:
      - libcfitsio-dev
      - libsharp-dev
      - libhealpix-cxx-dev

python:
   version: 3.7
   install:
      - method: pip
        path: .

submodules:
    include: all
